### ISSUE TITLE
期待！支持一下！

### ISSUE THREAD

**Issue by zhishao** [Aitical/SCNet#1]

**Comment by lihaocheng5201314** [comment]
> 啥时候上传模块代码！求求了，已经两周了，快更新吧哥！！

**Comment by Aitical** [comment]
感谢大家对SCNet的关注，近期我一直忙于其他论文的事情延误了这个工作的推进。 
感谢大家的提醒，刚刚已经更新了SCNet主干网络实现，可以在Basicsr库中进行验证。
预训练模型、测试结果以及消融结构验证和扩展模型的结果都会开源，近期整理好实验结果就会上传。

Thank you all for your keen interest in our project. Recently, I have been occupied with various manuscript submissions, which has slightly delayed the progress of this project. I'm pleased to share that this work is almost organized.

I'd like to express special thanks for your reminders. We have updated the code implementation for this project.

The pre-trained models, experimental results, as well as ablation studies and extended structures will all be open-sourced soon.

**Comment by gongyan1** [comment]
期待，加油！

**Comment by Shiqi72** [comment]
你好，什么时候上传完整代码，期待

**Comment by Aitical** [comment]
We have updated implementation, thanks for your attention!
