### ISSUE TITLE
训练细节

### ISSUE THREAD

**Issue by wangjg33** [Aitical/SCNet#4]
你好，这个工作是非常有吸引力的工作！

我在尝试复现的过程中，发现从头训练SCNet并没有达到论文的指标。SCNet-T，X2，训练后的PNSR 为 37.7444，与论文中的37.85相差较大。

我使用basicsr的训练框架。
训练的设置如下：
    gt_size: 64
    use_hflip: true
    use_rot: true

data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [500000]
    restart_weights: [1]
    eta_min: !!float 1e-5

  total_iter: 500000
  warmup_iter: -1  # no warm up

losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

能否提供一下您的训练yml文件，供我学习一下。感谢。

**Comment by Aitical** [comment]
感谢您对我们工作的关注！

您的这配置文件有两处需要注意的地方：
1. **gt_size: 64**    我们写的patch size是输入图像(LR image)的尺寸，参考BasicSR的实现中这里是GT大小，所以应该是128用于2倍任务，256用于4倍任务。我们的实验设置是和论文[1]一致，使用DF2K数据集，input patch size 64进行训练。此外，如果参考EDSR或者IMDN[2]的设置，在DIV2K上使用patch size 48进行训练，现在的论文中我们没有放出具体指标，这里给您一份2倍的SCNet-B供您复现参考，目前我们简单验证了下与IMDN对齐后的初步实验结果，后续我们会更新这个工作也会提升一下2倍的指标。

|Method| Params| Set5 | Set14| B100| Urban100| Manga109|
| :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| IMDN | 694K | 38.00/0.9605 | 33.63/0.9177 | 32.19/0.8996 | 32.17/0.9283 | 38.88/0.9774 |
| SCNet-B | 557K | 38.01/0.9606 | 33.64/0.9180 | 32.22/0.8999 | 32.17/0.9285 | 38.90/0.9776 |

2. **periods: [500000]
restart_weights: [1]** 学习率配置这里，建议您可以开启多个周期设置，例如每200K次迭代为一个周期 (这部分影响很小)。

感谢您对我们工作的关注，欢迎交流和讨论！


[1] Long Sun, Jinshan Pan, Jinhui Tang: ShuffleMixer: An Efficient ConvNet for Image Super-Resolution. NeurIPS 2022
[2] Hui, Zheng, et al. "Lightweight image super-resolution with information multi-distillation network." Proceedings of the 27th acm international conference on multimedia. 2019.

**Comment by wangjg33** [comment]
感谢您的回复，指出patchsize的问题。我尝试按您给的提示重新训练一下，谢谢。
