### ISSUE TITLE
size

### ISSUE THREAD

**Issue by Rzxxy** [Aitical/SCNet#5]
# Modified SRResNet w/o BN from:
# Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network

# ----------- Commands for running
# ----------- Single GPU with auto_resume
# PYTHONPATH="./:${PYTHONPATH}"  CUDA_VISIBLE_DEVICES=0 python basicsr/train.py -opt options/train/SRResNet_SRGAN/train_MSRResNet_x4.yml --auto_resume

# general settings
name: scnet
model_type: SRModel
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: datasets/DF2K_Flickr2Kx2/HR
    dataroot_lq: datasets/DF2K_Flickr2Kx2/LR

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/set5/x2crop/HR
    dataroot_lq: datasets/set5/x2crop/LR
    io_backend:
      type: disk

  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/set5/x2crop/HR
    dataroot_lq: datasets/set5/x2crop/LR
    io_backend:
      type: disk

# network structures
network_g:
  type: SCNet #MSRResNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 16
  upscale: 4

# path
path:
  pretrain_network_g: ~
  param_key_g: params
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [10000]
    restart_weights: [1]
    eta_min: !!float 1e-4

  total_iter: 10000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    niqe:
      type: calculate_niqe
      crop_border: 4
      better: lower  # the lower, the better

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
这是我的yml文件，图像尺寸分别为128x128和64x64但是在开始训练时出现如下报错：
UserWarning: Using a target size (torch.Size([32, 3, 128, 128])) that is different to the input size (torch.Size([32, 3, 256, 256])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(pred, target, reduction='none')
Traceback (most recent call last):
  File "C:\Users\Rzxxy\Desktop\BasicSR-master\basicsr\train.py", line 215, in <module>
    train_pipeline(root_path)
  File "C:\Users\Rzxxy\Desktop\BasicSR-master\basicsr\train.py", line 169, in train_pipeline
    model.optimize_parameters(current_iter)
  File "c:\users\rzxxy\desktop\basicsr-master\basicsr\models\sr_model.py", line 100, in optimize_parameters
    l_pix = self.cri_pix(self.output, self.gt)
  File "C:\Users\Rzxxy\.conda\envs\SR\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "c:\users\rzxxy\desktop\basicsr-master\basicsr\losses\basic_loss.py", line 52, in forward
    return self.loss_weight * l1_loss(pred, target, weight, reduction=self.reduction)
  File "c:\users\rzxxy\desktop\basicsr-master\basicsr\losses\loss_util.py", line 92, in wrapper
    loss = loss_func(pred, target, **kwargs)
  File "c:\users\rzxxy\desktop\basicsr-master\basicsr\losses\basic_loss.py", line 14, in l1_loss
    return F.l1_loss(pred, target, reduction='none')
  File "C:\Users\Rzxxy\.conda\envs\SR\lib\site-packages\torch\nn\functional.py", line 3263, in l1_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "C:\Users\Rzxxy\.conda\envs\SR\lib\site-packages\torch\functional.py", line 74, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (256) must match the size of tensor b (128) at non-singleton dimension 3
我是否理解错了论文中的size？

**Comment by Aitical** [comment]
您好，

type: SCNet #MSRResNet
num_in_ch: 3
num_out_ch: 3
num_feat: 64
num_block: 16
upscale: 4

这里SCNet模型使用的是4倍，但从Dataset和任务配置来看应该是2倍任务，所以导致了这个错误
您可以稍微注意下config文件中的setting 。最后PSNR/SSIM指标中，crop_board应当与scale一致，如果是2倍任务的话这里也应该是2。
